#!/usr/bin/env python3
"""
TinyDSP Instruction Simulator

This simulator executes TinyDSP assembly instructions and tracks register/memory state.
It's designed for verifying the correctness of code generated by the LLVM TinyDSP backend.
"""

import re
import sys
from typing import Dict, List, Tuple

class TinyDSPSimulator:
    """Simulates execution of TinyDSP assembly code."""
    
    def __init__(self):
        # Initialize 8 registers (R0-R7)
        self.regs = [0] * 8
        # Memory: byte-addressable, 64KB
        self.memory = bytearray(65536)
        # Program counter
        self.pc = 0
        # Execution trace for debugging
        self.trace = []
        
    def reset(self):
        """Reset simulator state."""
        self.regs = [0] * 8
        self.memory = bytearray(65536)
        self.pc = 0
        self.trace = []
        
    def load_memory(self, address: int, data: bytes):
        """Load data into memory at specified address."""
        for i, byte in enumerate(data):
            self.memory[address + i] = byte
            
    def read_word(self, address: int) -> int:
        """Read 32-bit word from memory (little-endian)."""
        return int.from_bytes(self.memory[address:address+4], 'little')
    
    def write_word(self, address: int, value: int):
        """Write 32-bit word to memory (little-endian)."""
        self.memory[address:address+4] = (value & 0xFFFFFFFF).to_bytes(4, 'little')
    
    def sign_extend(self, value: int, bits: int) -> int:
        """Sign-extend a value from 'bits' bits to 32 bits."""
        if value & (1 << (bits - 1)):
            return value | (~((1 << bits) - 1))
        return value
    
    def parse_asm_line(self, line: str) -> Tuple[str, List[str]]:
        """Parse an assembly line into opcode and operands."""
        # Remove comments
        line = re.sub(r'#.*$', '', line)
        line = line.strip()
        
        if not line or line.startswith('.'):
            return None, []
        
        # Split into opcode and operands
        parts = line.split(None, 1)
        if not parts:
            return None, []
        
        opcode = parts[0].upper()
        operands = []
        
        if len(parts) > 1:
            # Parse operands
            op_str = parts[1]
            # Split by comma, handling memory operands like [r7 + 4]
            op_str = re.sub(r'\s+', '', op_str)
            operands = [op.strip() for op in re.split(r',(?![^\[]*\])', op_str)]
        
        return opcode, operands
    
    def parse_register(self, reg_str: str) -> int:
        """Parse register name to register number."""
        reg_str = reg_str.lower().strip()
        if reg_str.startswith('r'):
            return int(reg_str[1:])
        raise ValueError(f"Invalid register: {reg_str}")
    
    def parse_immediate(self, imm_str: str) -> int:
        """Parse immediate value."""
        imm_str = imm_str.strip()
        if imm_str.startswith('0x'):
            return int(imm_str, 16)
        elif imm_str.startswith('-'):
            return int(imm_str)
        else:
            return int(imm_str)
    
    def parse_memory_operand(self, mem_str: str) -> Tuple[int, int]:
        """Parse memory operand [base + offset] -> (base_reg, offset)."""
        # Remove brackets
        mem_str = mem_str.strip()[1:-1]
        
        # Check for offset
        if '+' in mem_str:
            parts = mem_str.split('+')
            base_reg = self.parse_register(parts[0])
            offset = self.parse_immediate(parts[1])
        elif '-' in mem_str and mem_str.count('-') == 1:
            parts = mem_str.split('-')
            base_reg = self.parse_register(parts[0])
            offset = -self.parse_immediate(parts[1])
        else:
            base_reg = self.parse_register(mem_str)
            offset = 0
        
        return base_reg, offset
    
    def execute_instruction(self, opcode: str, operands: List[str]) -> bool:
        """Execute a single instruction. Returns False if RET encountered."""
        trace_entry = f"{opcode} {', '.join(operands)}"
        
        if opcode == "ADD":
            rd = self.parse_register(operands[0])
            rs1 = self.parse_register(operands[1])
            rs2 = self.parse_register(operands[2])
            self.regs[rd] = (self.regs[rs1] + self.regs[rs2]) & 0xFFFFFFFF
            
        elif opcode == "SUB":
            rd = self.parse_register(operands[0])
            rs1 = self.parse_register(operands[1])
            rs2 = self.parse_register(operands[2])
            self.regs[rd] = (self.regs[rs1] - self.regs[rs2]) & 0xFFFFFFFF
            
        elif opcode == "MUL":
            rd = self.parse_register(operands[0])
            rs1 = self.parse_register(operands[1])
            rs2 = self.parse_register(operands[2])
            self.regs[rd] = (self.regs[rs1] * self.regs[rs2]) & 0xFFFFFFFF
            
        elif opcode == "AND":
            rd = self.parse_register(operands[0])
            rs1 = self.parse_register(operands[1])
            rs2 = self.parse_register(operands[2])
            self.regs[rd] = self.regs[rs1] & self.regs[rs2]
            
        elif opcode == "OR":
            rd = self.parse_register(operands[0])
            rs1 = self.parse_register(operands[1])
            rs2 = self.parse_register(operands[2])
            self.regs[rd] = self.regs[rs1] | self.regs[rs2]
            
        elif opcode == "XOR":
            rd = self.parse_register(operands[0])
            rs1 = self.parse_register(operands[1])
            rs2 = self.parse_register(operands[2])
            self.regs[rd] = self.regs[rs1] ^ self.regs[rs2]
            
        elif opcode == "ADDI":
            rd = self.parse_register(operands[0])
            rs1 = self.parse_register(operands[1])
            imm = self.parse_immediate(operands[2])
            imm = self.sign_extend(imm, 18)
            self.regs[rd] = (self.regs[rs1] + imm) & 0xFFFFFFFF
            
        elif opcode == "LOAD":
            rd = self.parse_register(operands[0])
            base_reg, offset = self.parse_memory_operand(operands[1])
            addr = (self.regs[base_reg] + offset) & 0xFFFFFFFF
            self.regs[rd] = self.read_word(addr)
            
        elif opcode == "STORE":
            rs = self.parse_register(operands[0])
            base_reg, offset = self.parse_memory_operand(operands[1])
            addr = (self.regs[base_reg] + offset) & 0xFFFFFFFF
            self.write_word(addr, self.regs[rs])
            
        elif opcode == "RET":
            self.trace.append(f"{trace_entry} -> RETURN")
            return False
            
        elif opcode == "MOV":
            rd = self.parse_register(operands[0])
            rs = self.parse_register(operands[1])
            self.regs[rd] = self.regs[rs]
            
        elif opcode == "LI":
            rd = self.parse_register(operands[0])
            imm = self.parse_immediate(operands[1])
            self.regs[rd] = imm & 0xFFFFFFFF
            
        else:
            raise ValueError(f"Unknown instruction: {opcode}")
        
        self.trace.append(f"{trace_entry} -> R={self.regs[:8]}")
        return True
    
    def run_asm(self, asm_code: str):
        """Run assembly code."""
        lines = asm_code.strip().split('\n')
        
        for line in lines:
            opcode, operands = self.parse_asm_line(line)
            if opcode is None:
                continue
            
            if not self.execute_instruction(opcode, operands):
                break  # RET encountered
    
    def get_register(self, reg_num: int) -> int:
        """Get register value."""
        return self.regs[reg_num]
    
    def print_state(self):
        """Print current simulator state."""
        print("Registers:")
        for i in range(8):
            print(f"  R{i}: 0x{self.regs[i]:08x} ({self.regs[i]})")
        print(f"\nExecution trace:")
        for entry in self.trace:
            print(f"  {entry}")


def test_simple_add():
    """Test simple addition."""
    sim = TinyDSPSimulator()
    
    # Test: R0 = 5 + 3
    asm = """
        li r1, 5
        li r2, 3
        add r0, r1, r2
        ret
    """
    
    sim.run_asm(asm)
    assert sim.get_register(0) == 8, f"Expected R0=8, got {sim.get_register(0)}"
    print("✓ Test simple_add passed")


def test_memory():
    """Test memory load/store."""
    sim = TinyDSPSimulator()
    
    # Test: Store and load
    asm = """
        li r7, 0x1000
        li r1, 42
        store r1, [r7 + 0]
        load r2, [r7 + 0]
        ret
    """
    
    sim.run_asm(asm)
    assert sim.get_register(2) == 42, f"Expected R2=42, got {sim.get_register(2)}"
    print("✓ Test memory passed")


def test_arithmetic():
    """Test various arithmetic operations."""
    sim = TinyDSPSimulator()
    
    asm = """
        li r1, 10
        li r2, 3
        sub r3, r1, r2
        mul r4, r1, r2
        ret
    """
    
    sim.run_asm(asm)
    assert sim.get_register(3) == 7, f"Expected R3=7, got {sim.get_register(3)}"
    assert sim.get_register(4) == 30, f"Expected R4=30, got {sim.get_register(4)}"
    print("✓ Test arithmetic passed")


if __name__ == "__main__":
    print("TinyDSP Simulator - Running tests...\n")
    
    test_simple_add()
    test_memory()
    test_arithmetic()
    
    print("\n✅ All tests passed!")
